### ISSUE TITLE
about BiSeNet ckpt

### ISSUE THREAD

**Issue by sicong-li** [ZPdesu/Barbershop#21]
Hi, I would like to know what dataset is the BiSeNet model trained on in your project, or which project is the BiSeNet ckpt downloaded, thank you

**Comment by LiUzHiAn** [comment]
Maybe this repo can help, https://github.com/zllrunning/face-parsing.PyTorch

**Comment by sicong-li** [comment]
@LiUzHiAn Thanks. This is what i want!
